TodoDiary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todos.urls')),
]

todos/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.todo, name='todo'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('index/', views.index, name='index'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

todos/models.py
from email.policy import default
from django.db import models
# Create your models here.

class TodoDiary(models.Model):
    id = models.IntegerField(primary_key=True)
    todos = models.JSONField(default=dict)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

todos/views.py
from django.shortcuts import render, redirect

from todos.models import TodoDiary

todo_num = 0

# Create your views here.
def todo(request):
    return render(request, 'todos/todo.html')

def new(request):
    return render(request, 'todos/new.html')

def create(request):
    todo_data = {}
    global todo_num
    todo_num = int(request.GET.get('todo_num'))

    for i in range(todo_num):
        str_num = str(i)
        str_hidden_num = str_num + 'hidden'
        str_name = 'todo' + str_num
        check_name = 'check' + str_num

        if request.GET.get(check_name) == '1':
            todo_data[str_hidden_num] = request.GET.get(str_name)
        else:
            todo_data[str_num] = request.GET.get(str_name)

    content = request.GET.get('content')

    diary = TodoDiary(todos=todo_data, content=content)
    diary.save()
    return redirect('todos:index')

def index(request):
    diarys = TodoDiary.objects.order_by('-pk')
    check = []
    for i in range(todo_num):
        name = str(i) + 'hidden'
        check.append(name)
        
    context = {
        'diarys': diarys,
        'check': check,
    }
    return render(request, 'todos/index.html', context)

def delete(request, pk):
    diary = TodoDiary.objects.get(pk=pk)
    diary.delete()

    return redirect('todos:index')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block style %}{% endblock style %}
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  {% block java %}
  {% endblock java %}
</body>
</html>

todos/templates/todos/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock style %}

{% block content %}
  <h1>DIARY</h1>
  <hr>
  {% for diary in diarys %}
    <p>{{ diary.pk }}번) {{ diary.created_at }}</p>
    <ul>
      {% for key, value in diary.todos.items %}
        <li>
          {% if key in check %} 
            <p class="done"> {{ value }}</p>
          {% else %}
            <p> {{ value }}</p>
          {% endif %} 
        </li>
      {% endfor %}
    </ul>
    <p>content: {{ diary.content }}</p>
    <a href="{% url 'todos:delete' diary.pk %}">🗑</a>  
    <hr>
  {% endfor %}
  <a href="{% url 'todos:todo' %}">📝</a>
{% endblock content %}

{% block java %}
{% endblock java %}

todos/templates/todos/new.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock style %}

{% block content %}
  <form action="{% url 'todos:create' %}" method="GET">
    
    <ul id="todo-list">
    </ul>
    <div class="textarea">
      <textarea name="content" id="content" cols="30" rows="10" required></textarea>
    </div>
    <br>
    <div class="submit-button">
      <input type="submit" class="submit" value="Submit">
    </div>
  </form>
  <div class="back">
    <a href="{% url 'todos:todo' %}">📝</a>
  </div>
{% endblock content %}

{% block java %}
  <script src="{% static 'todos/js/savetodo.js' %}"></script>
{% endblock java %}

todos/templates/todos/todo.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock style %}


{% block content %}
  <div class="card">
    <h2 id="today"></h2>
    <h2 id="clock"></h2>

    <form id="todo-form">
      <input type="text" placeholder="  오늘의 계획을 적어주세요." required>
    </form>

    <ul id="todo-list"></ul>

    <div class="atag">
      <a class="gotod" href="{% url 'todos:index' %}">📅</a>
      <a class="save" href="{% url 'todos:new' %}">💾</a>
    </div>
  </div>

  <img id="bgImage" src="{% static 'todos/img/3.jpg'%}" alt="backgroung">
{% endblock content %}

{% block java %}
  <script src="{% static 'todos/js/todolist.js' %}"></script>
  <script src="{% static 'todos/js/clock.js' %}"></script>
  <script src="{% static 'todos/js/background.js' %}"></script>
{% endblock java %}